// ─────────────────────────────────────────────────────────────────────
// Structured quote options.
//
// Drivers must not send free text to customers before the booking
// deposit is paid. Quotes are submitted as 1–3 structured options built
// only from the trusted enums below. Labels and descriptions are always
// generated by the app — driver-supplied labels/descriptions/messages
// are rejected server-side.
// ─────────────────────────────────────────────────────────────────────

export const SERVICE_LEVELS = {
  transport_only: {
    label: "Transport only",
    description: "Customer loads and unloads. Driver provides van and transport only.",
  },
  one_man_loading: {
    label: "1 man and van",
    description: "Driver helps with loading, transport and unloading.",
  },
  two_men_loading: {
    label: "2 men and van",
    description: "Two movers help with loading, transport and unloading.",
  },
  two_men_luton: {
    label: "2 men and Luton van",
    description: "Two movers, Luton van, loading and unloading included.",
  },
} as const;

export const VAN_SIZES = {
  small_van: { label: "Small van" },
  medium_van: { label: "Medium van" },
  luton_van: { label: "Luton van" },
  suitable_van: { label: "Suitable van provided" },
} as const;

export type ServiceLevelKey = keyof typeof SERVICE_LEVELS;
export type VanSizeKey = keyof typeof VAN_SIZES;

export interface QuoteOption {
  id: string;
  serviceLevel: ServiceLevelKey;
  serviceLabel: string;
  serviceDescription: string;
  vanSize: VanSizeKey;
  vanLabel: string;
  totalPrice: number;
}

export const STANDARD_QUOTE_ASSUMPTION =
  "This quote is based on the move details provided. The price may change if the item list, access, parking, waiting time, distance, or move date changes.";

export const MIN_OPTION_PRICE = 10;
export const MAX_OPTION_PRICE = 10000;
export const MAX_OPTIONS = 3;

function isValidPrice(value: unknown): value is number {
  return (
    typeof value === "number" &&
    Number.isFinite(value) &&
    value >= MIN_OPTION_PRICE &&
    value <= MAX_OPTION_PRICE
  );
}

/**
 * Validates raw driver-submitted options. Only serviceLevel, vanSize and
 * totalPrice are read from the input — ids, labels and descriptions are
 * regenerated from the trusted enums so no driver text can reach the
 * customer. Throws with a customer-safe message on invalid input.
 */
export function validateQuoteOptions(raw: unknown): QuoteOption[] {
  if (!Array.isArray(raw) || raw.length < 1 || raw.length > MAX_OPTIONS) {
    throw new Error(`Please submit between 1 and ${MAX_OPTIONS} quote options.`);
  }

  const seen = new Set<string>();

  return raw.map((item: any, index: number) => {
    const serviceLevel = String(item?.serviceLevel || "") as ServiceLevelKey;
    const vanSize = String(item?.vanSize || "") as VanSizeKey;
    const totalPrice = typeof item?.totalPrice === "number" ? item.totalPrice : Number(item?.totalPrice);

    if (!SERVICE_LEVELS[serviceLevel]) {
      throw new Error(`Option ${index + 1}: please choose a valid service level.`);
    }
    if (!VAN_SIZES[vanSize]) {
      throw new Error(`Option ${index + 1}: please choose a valid van size.`);
    }
    if (!isValidPrice(totalPrice)) {
      throw new Error(
        `Option ${index + 1}: total price must be between £${MIN_OPTION_PRICE} and £${MAX_OPTION_PRICE.toLocaleString("en-GB")}.`
      );
    }

    const dedupeKey = `${serviceLevel}|${vanSize}`;
    if (seen.has(dedupeKey)) {
      throw new Error(`Option ${index + 1}: duplicate service level and van size combination.`);
    }
    seen.add(dedupeKey);

    const rounded = Math.round(totalPrice * 100) / 100;

    return {
      id: `option_${index + 1}`,
      serviceLevel,
      serviceLabel: SERVICE_LEVELS[serviceLevel].label,
      serviceDescription: SERVICE_LEVELS[serviceLevel].description,
      vanSize,
      vanLabel: VAN_SIZES[vanSize].label,
      totalPrice: rounded,
    };
  });
}

/** Parse quote_options from the database defensively. */
export function parseStoredQuoteOptions(raw: unknown): QuoteOption[] {
  if (!raw) return [];
  let value = raw;
  if (typeof raw === "string") {
    try {
      value = JSON.parse(raw);
    } catch {
      return [];
    }
  }
  if (!Array.isArray(value)) return [];
  return value.filter(
    (o: any) =>
      o &&
      typeof o.id === "string" &&
      SERVICE_LEVELS[o.serviceLevel as ServiceLevelKey] &&
      VAN_SIZES[o.vanSize as VanSizeKey] &&
      typeof o.totalPrice === "number" &&
      o.totalPrice > 0
  ).map((o: any) => ({
    id: o.id,
    serviceLevel: o.serviceLevel,
    serviceLabel: SERVICE_LEVELS[o.serviceLevel as ServiceLevelKey].label,
    serviceDescription: SERVICE_LEVELS[o.serviceLevel as ServiceLevelKey].description,
    vanSize: o.vanSize,
    vanLabel: VAN_SIZES[o.vanSize as VanSizeKey].label,
    totalPrice: o.totalPrice,
  }));
}
