-- West Midlands Cleaner - cleaner onboarding storage setup
-- Run this in Supabase SQL editor if the cleaner document bucket does not already exist.
-- The website API uploads files with the service role key, so the bucket should remain PRIVATE.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'cleaner-documents',
  'cleaner-documents',
  false,
  10485760,
  array['application/pdf', 'image/jpeg', 'image/png']
)
on conflict (id) do update
set
  public = false,
  file_size_limit = 10485760,
  allowed_mime_types = array['application/pdf', 'image/jpeg', 'image/png'];

-- No public storage policy is required because cleaner documents should not be public.
-- Admin document access is generated by the server using short-lived signed URLs.
